version: '3'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: airport_django
    
    volumes:
      - .:/app
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"