# Generated by Django 3.1.2 on 2020-10-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport_place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('town', models.CharField(max_length=100)),
                ('runway_num', models.PositiveIntegerField()),
                ('large_parkings', models.PositiveIntegerField()),
                ('small_parkings', models.PositiveIntegerField()),
                ('airport_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
