# Generated by Django 3.1.2 on 2020-10-30 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airplains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_sign', models.CharField(max_length=20)),
                ('ssh_key', models.CharField(max_length=255)),
                ('ssh_pub', models.CharField(max_length=255)),
                ('state', models.PositiveIntegerField(choices=[(0, 'PARKED'), (1, 'TAKE-OFF'), (2, 'AIRBORNE'), (3, 'APPROACH'), (4, 'LANDED')], default=0)),
            ],
        ),
    ]
