# Generated by Django 3.1.2 on 2020-10-30 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airplains', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airplains',
            name='plain_type',
            field=models.PositiveIntegerField(choices=[(0, 'AIRLINER'), (1, 'PRIVATE')], default=0),
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=14, max_digits=20)),
                ('longitude', models.DecimalField(decimal_places=14, max_digits=20)),
                ('altitude', models.IntegerField()),
                ('heading', models.IntegerField()),
                ('position_time', models.DateTimeField(auto_now_add=True)),
                ('plain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airplains.airplains')),
            ],
            options={
                'ordering': ['-position_time'],
            },
        ),
    ]
