# Generated by Django 3.1.2 on 2020-10-30 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aiport_place', '0001_initial'),
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='airport',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aiport_place.airport_place'),
            preserve_default=False,
        ),
    ]
