# Generated by Django 3.1.2 on 2020-10-30 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aiport_place', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groundcrew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runway_clear', models.BooleanField(default=False)),
                ('airport', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='aiport_place.airport_place')),
            ],
        ),
    ]
